import { chromium } from "playwright-core";
import { mkdir } from "node:fs/promises";

const outputDir = "/home/ubuntu/khabir-alshawahid-prototype/.tmp-director-smoke";
await mkdir(outputDir, { recursive: true });

const browser = await chromium.launch({ executablePath: "/usr/bin/chromium", headless: true, args: ["--no-sandbox", "--disable-dev-shm-usage"] });

try {
  const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
  const unexpectedDataRequests = [];
  page.on("request", (request) => {
    if (["xhr", "fetch"].includes(request.resourceType()) && !request.url().includes("analytics")) unexpectedDataRequests.push(request.url());
  });
  await page.addInitScript(() => {
    Object.defineProperty(navigator, "canShare", { configurable: true, value: () => true });
    Object.defineProperty(navigator, "share", { configurable: true, value: async (payload) => { window.__directorShare = payload; } });
    Object.defineProperty(navigator, "clipboard", { configurable: true, value: { writeText: async (text) => { window.__directorClipboard = text; } } });
  });
  await page.goto("http://127.0.0.1:3000/director", { waitUntil: "networkidle" });
  const suggestedHijriYear = await page.evaluate(() => {
    const value = new Intl.DateTimeFormat("en-u-ca-islamic-umalqura", { year: "numeric" }).formatToParts(new Date()).find((part) => part.type === "year")?.value;
    return value ? new Intl.NumberFormat("ar-SA-u-nu-arab", { useGrouping: false }).format(Number(value)) : "";
  });
  const directorAcademicYear = page.getByRole("region", { name: "العام الدراسي للمدير" });
  await directorAcademicYear.getByText(suggestedHijriYear, { exact: true }).waitFor();
  await directorAcademicYear.getByLabel("تعديل العام الدراسي للمدير").click();
  await directorAcademicYear.getByLabel("تحرير العام الدراسي للمدير").fill("١٤٤٧");
  await directorAcademicYear.getByRole("button", { name: "حفظ", exact: true }).click();
  await directorAcademicYear.getByText("١٤٤٧", { exact: true }).waitFor();
  await page.reload({ waitUntil: "networkidle" });
  await page.getByRole("region", { name: "العام الدراسي للمدير" }).getByText("١٤٤٧", { exact: true }).waitFor();
  if (await page.locator(".director-intro p").isVisible() || await page.locator(".director-empty-review").isVisible() || await page.locator(".director-review").isVisible()) throw new Error("Director mobile still renders redundant introductory content");
  if (await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth + 1)) throw new Error("Director mobile layout has horizontal overflow");
  await page.getByRole("region", { name: "خطوة البداية للمدير" }).getByRole("heading", { name: "ابدأ بفريق صغير", exact: true }).waitFor();
  if (await page.getByRole("progressbar", { name: "نسبة تقييم الملفات" }).getAttribute("aria-valuenow") !== "0") throw new Error("Evaluation progress should start at zero without local files");
  await page.getByRole("button", { name: "نسخ رسالة بداية", exact: true }).click();
  const starterText = await page.evaluate(() => window.__directorClipboard);
  if (!starterText.includes("لا يحتاج التطبيق إلى حساب") || !starterText.includes("شاهد واحد")) throw new Error("Director starter message is not suitable for local adoption");
  await page.getByRole("button", { name: "إعداد قالب واتساب الافتراضي", exact: true }).click();
  const templateDialog = page.getByRole("dialog", { name: "إعداد قالب واتساب الافتراضي" });
  await templateDialog.getByLabel("قالب رسالة واتساب الافتراضي").fill("عزيزتي {{teacherName}}،\nيرجى استكمال المطلوب.\n{{comment}}\n{{directorName}}");
  await templateDialog.getByRole("button", { name: "تم", exact: true }).click();
  await page.getByRole("button", { name: "استيراد ملف PDF", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "استيراد ملف أداء" });
  await dialog.getByLabel("اسم المعلم/المعلمة").fill("أمل السهلي");
  await dialog.getByLabel("الفصل الدراسي عند الاستيراد").selectOption("الأول");
  await dialog.locator(".director-file-input").setInputFiles({ name: "ملف-الأداء-أمل.pdf", mimeType: "application/pdf", buffer: Buffer.from("%PDF-1.4\n1 0 obj\n<<>>\nendobj\ntrailer\n<<>>\n%%EOF") });
  await dialog.getByRole("button", { name: "حفظ محلي ومتابعة", exact: true }).click();
  await page.getByRole("heading", { name: "أمل السهلي", exact: true }).waitFor();
  await page.locator(".review-form select").nth(0).selectOption("reviewed");
  await page.locator(".review-form select").nth(1).selectOption("متميز");
  await page.getByPlaceholder("اكتب ملاحظة واضحة ومهنية…").fill("ملف مرتب ويظهر أثرًا مهنيًا واضحًا.");
  await page.getByPlaceholder("اكتب ملاحظة واضحة ومهنية…").blur();
  await page.locator(".review-form select").nth(0).selectOption("follow_up");
  await page.getByRole("region", { name: "رسالة واتساب للمتابعة" }).waitFor();
  if (!/عزيزتي أمل السهلي/.test(await page.getByLabel("نص الرسالة").inputValue()) || !/ملف مرتب ويظهر أثرًا مهنيًا واضحًا/.test(await page.getByLabel("نص الرسالة").inputValue())) throw new Error("Stored WhatsApp template did not resolve teacher and comment variables");
  const whatsAppNumber = page.getByLabel("رقم واتساب المعلم");
  await whatsAppNumber.fill("+966 500 000 001");
  await whatsAppNumber.blur();
  const whatsAppMessage = page.getByLabel("نص الرسالة");
  await whatsAppMessage.fill("يرجى استكمال الشواهد المرفقة قبل الاعتماد.");
  await whatsAppMessage.blur();
  await page.evaluate(() => { window.__whatsAppUrl = ""; window.open = (url) => { window.__whatsAppUrl = String(url); return {}; }; });
  await page.getByRole("button", { name: "فتح واتساب للمراجعة", exact: true }).click();
  const whatsAppUrl = await page.evaluate(() => window.__whatsAppUrl);
  if (!whatsAppUrl.startsWith("https://wa.me/966500000001?text=") || !decodeURIComponent(whatsAppUrl).includes("يرجى استكمال الشواهد")) throw new Error("WhatsApp follow-up link did not preserve the local number and message");
  await page.reload({ waitUntil: "networkidle" });
  if (await page.locator(".review-form select").nth(0).inputValue() !== "follow_up") throw new Error("Follow-up status did not persist locally");
  if (await page.locator(".review-form select").nth(1).inputValue() !== "متميز") throw new Error("Review level did not persist locally");
  if (await page.getByLabel("الفصل الدراسي للملف").inputValue() !== "الأول") throw new Error("Academic term did not persist locally");
  if (await page.getByPlaceholder("اكتب ملاحظة واضحة ومهنية…").inputValue() !== "ملف مرتب ويظهر أثرًا مهنيًا واضحًا.") throw new Error("Review comment did not persist locally");
  if (await page.getByLabel("رقم واتساب المعلم").inputValue() !== "+966 500 000 001") throw new Error("WhatsApp number did not persist locally");
  if (await page.getByLabel("نص الرسالة").inputValue() !== "يرجى استكمال الشواهد المرفقة قبل الاعتماد.") throw new Error("WhatsApp message did not persist locally");
  await page.locator(".review-form select").nth(0).selectOption("reviewed");
  await page.getByRole("button", { name: "استيراد ملف PDF", exact: true }).click();
  const secondDialog = page.getByRole("dialog", { name: "استيراد ملف أداء" });
  await secondDialog.getByLabel("اسم المعلم/المعلمة").fill("سارة الحربي");
  await secondDialog.getByLabel("الفصل الدراسي عند الاستيراد").selectOption("العام الدراسي");
  await secondDialog.locator(".director-file-input").setInputFiles({ name: "ملف-الأداء-سارة.pdf", mimeType: "application/pdf", buffer: Buffer.from("%PDF-1.4\n1 0 obj\n<<>>\nendobj\ntrailer\n<<>>\n%%EOF") });
  await secondDialog.getByRole("button", { name: "حفظ محلي ومتابعة", exact: true }).click();
  if (await page.getByRole("progressbar", { name: "نسبة تقييم الملفات" }).getAttribute("aria-valuenow") !== "50") throw new Error("Evaluation progress did not update after one reviewed local file");
  if (await page.locator(".evaluation-track .is-reviewed").getAttribute("style") !== "width: 50%;") throw new Error("Reviewed segment did not render its visual progress width");
  if (await page.locator(".evaluation-track .is-new").getAttribute("style") !== "width: 50%;") throw new Error("Pending segment did not render its visual progress width");
  await page.getByRole("tab", { name: "المتابعة", exact: true }).click();
  await page.getByRole("heading", { name: "لوحة المتابعة", exact: true }).waitFor();
  if (!/مكتملة 50%/.test(await page.getByRole("img", { name: /رسم مقارنة حالة الملفات/ }).getAttribute("aria-label"))) throw new Error("Dashboard chart did not display the completed-file percentage");
  await page.screenshot({ path: `${outputDir}/dashboard-chart.png`, fullPage: false });
  const [csvRegisterDownload] = await Promise.all([page.waitForEvent("download", { timeout: 60000 }), page.getByRole("button", { name: "تنزيل CSV", exact: true }).click()]);
  await csvRegisterDownload.saveAs(`${outputDir}/teacher-register.csv`);
  if (await csvRegisterDownload.failure()) throw new Error("Teacher register CSV download failed");
  const [excelRegisterDownload] = await Promise.all([page.waitForEvent("download", { timeout: 60000 }), page.getByRole("button", { name: "تنزيل سجل Excel", exact: true }).click()]);
  await excelRegisterDownload.saveAs(`${outputDir}/teacher-register.xlsx`);
  if (await excelRegisterDownload.failure()) throw new Error("Teacher register Excel download failed");
  if (await page.locator(".dashboard-stats article").nth(0).getByText("2", { exact: true }).count() !== 1) throw new Error("Dashboard total does not aggregate local submissions");
  if (await page.locator(".dashboard-stats article").nth(1).getByText("1", { exact: true }).count() !== 1) throw new Error("Dashboard reviewed count is incorrect");
  if (await page.locator(".dashboard-stats article").nth(2).getByText("0", { exact: true }).count() !== 1) throw new Error("Dashboard follow-up count is incorrect");
  if (await page.locator(".dashboard-stats article").nth(3).getByText("50%", { exact: true }).count() !== 1) throw new Error("Dashboard completion percentage is incorrect");
  if (!/متميز\s+1/.test(await page.locator(".level-breakdown").innerText())) throw new Error("Dashboard review-level breakdown is incorrect");
  if (await page.locator(".dashboard-compare-list button").count() !== 2) throw new Error("Dashboard comparison list is incomplete");
  await page.locator(".dashboard-compare-heading select").selectOption("name");
  await page.locator(".dashboard-compare-list button").filter({ hasText: "أمل السهلي" }).click();
  await page.setViewportSize({ width: 1280, height: 900 });
  await page.reload({ waitUntil: "networkidle" });
  await page.locator(".director-list button").filter({ hasText: "أمل السهلي" }).click();
  if (await page.locator(".review-form select").nth(0).inputValue() !== "reviewed") throw new Error("Director local review did not restore on desktop");
  await page.evaluate(() => {
    window.__directorPrint = { markup: "", printed: false };
    window.open = () => ({
      document: { write: (markup) => { window.__directorPrint.markup = markup; }, close: () => undefined },
      focus: () => undefined,
      print: () => { window.__directorPrint.printed = true; },
    });
  });
  await page.getByRole("button", { name: "طباعة الملخص", exact: true }).click();
  await page.waitForFunction(() => window.__directorPrint.printed && window.__directorPrint.markup.includes("ملخص تقييم ملف الأداء") && window.__directorPrint.markup.includes('dir="rtl"') && !window.__directorPrint.markup.includes("تقييم محلي أُعد على جهاز المدير"), { timeout: 30000 });
  await page.getByRole("button", { name: "مشاركة الملخص", exact: true }).click();
  await page.waitForFunction(() => window.__directorShare?.files?.[0]?.name?.startsWith("ملخص-تقييم-") === true, { timeout: 60000 });
  await page.evaluate(() => Object.defineProperty(navigator, "canShare", { configurable: true, value: () => false }));
  const [download] = await Promise.all([page.waitForEvent("download", { timeout: 60000 }), page.getByRole("button", { name: "مشاركة الملخص", exact: true }).click()]);
  await download.saveAs(`${outputDir}/director-review-fallback.pdf`);
  if (await download.failure()) throw new Error("Director review fallback download failed");
  await page.getByRole("tab", { name: "التقرير", exact: true }).click();
  await page.getByRole("heading", { name: "التقرير التجميعي", exact: true }).waitFor();
  if (unexpectedDataRequests.length) throw new Error(`Aggregate report made an unexpected data request: ${unexpectedDataRequests.join(", ")}`);
  await page.locator(".aggregate-report-controls input").nth(0).fill("تقرير متابعة المدرسة");
  await page.locator(".aggregate-report-controls input").nth(1).fill("الفصل الدراسي الأول");
  if (await page.locator(".aggregate-preview-table tbody tr").count() !== 2) throw new Error("Aggregate report preview did not include all local files");
  const desktopPreview = await page.locator(".aggregate-report-preview").boundingBox();
  if (!desktopPreview || Math.abs((desktopPreview.width / desktopPreview.height) - (297 / 210)) > 0.12 || await page.locator(".aggregate-report-preview").getAttribute("data-paper-size") !== "a4-landscape") throw new Error("Aggregate report preview does not use an A4 landscape frame");
  const academicTermSelector = page.getByLabel("الفصل الدراسي في التقرير");
  if (!await academicTermSelector.locator('option[value="العام الدراسي"]').count() || await academicTermSelector.locator('option[value="الصيفي"]').count()) throw new Error("Director academic-term options did not replace the summer term with the academic year");
  await academicTermSelector.selectOption("العام الدراسي");
  if (await page.locator(".aggregate-preview-table tbody tr").count() !== 1 || !/سارة الحربي/.test(await page.locator(".aggregate-preview-table").innerText()) || !/الفصل الدراسي: العام الدراسي/.test(await page.locator(".aggregate-report-preview header").innerText())) throw new Error("Academic-year filter did not include the imported annual record");
  await page.getByLabel("الفصل الدراسي في التقرير").selectOption("الأول");
  if (await page.locator(".aggregate-preview-table tbody tr").count() !== 1 || !/أمل السهلي/.test(await page.locator(".aggregate-preview-table").innerText())) throw new Error("Aggregate report term filter did not include only the selected term");
  if (!/الفصل الدراسي: الفصل الدراسي الأول/.test(await page.locator(".aggregate-report-preview header").innerText())) throw new Error("Aggregate report preview does not disclose the selected term");
  await page.getByLabel("الفصل الدراسي في التقرير").selectOption("");
  const today = new Date().toISOString().slice(0, 10);
  await page.getByLabel("من تاريخ الاستيراد").fill(today);
  if (await page.locator(".aggregate-preview-table tbody tr").count() !== 2) throw new Error("Aggregate report start-date filter did not include imported files");
  await page.getByLabel("من تاريخ الاستيراد").fill("2099-01-01");
  if (!/لا توجد ملفات ضمن هذا النطاق/.test(await page.locator(".aggregate-preview-table tbody").innerText())) throw new Error("Aggregate report date filter did not exclude out-of-range files");
  await page.getByRole("button", { name: "مسح فلاتر التقرير", exact: true }).click();
  if (await page.locator(".aggregate-preview-table tbody tr").count() !== 2) throw new Error("Aggregate report filter clear did not restore local files");
  await page.getByLabel("البحث باسم المعلم في التقرير").fill("امل");
  if (await page.locator(".aggregate-preview-table tbody tr").count() !== 1 || !/أمل السهلي/.test(await page.locator(".aggregate-preview-table").innerText())) throw new Error("Aggregate report teacher-name search did not match Arabic name variants");
  if (!/اسم المعلم: امل/.test(await page.locator(".aggregate-report-preview header").innerText())) throw new Error("Aggregate report preview does not disclose the teacher-name search");
  await page.getByRole("button", { name: "مسح فلاتر التقرير", exact: true }).click();
  if (await page.locator(".aggregate-preview-table tbody tr").count() !== 2) throw new Error("Aggregate report search clear did not restore local files");
  await page.screenshot({ path: `${outputDir}/aggregate-preview.png`, fullPage: true });
  await page.getByRole("button", { name: "تمت مراجعتها", exact: true }).click();
  if (await page.locator(".aggregate-preview-table tbody tr").count() !== 1) throw new Error("Aggregate report scope did not filter reviewed files");
  await page.getByRole("button", { name: "كل الملفات", exact: true }).click();
  await page.getByLabel("الفصل الدراسي في التقرير").selectOption("الأول");
  const [excelDownload] = await Promise.all([page.waitForEvent("download", { timeout: 60000 }), page.getByRole("button", { name: "تنزيل Excel", exact: true }).click()]);
  await excelDownload.saveAs(`${outputDir}/aggregate-filtered.xlsx`);
  if (await excelDownload.failure()) throw new Error("Aggregate Excel download failed");
  await page.evaluate(() => { window.__directorPrint = { markup: "", printed: false }; });
  await page.getByRole("button", { name: "طباعة", exact: true }).click();
  await page.waitForFunction(() => window.__directorPrint.printed && window.__directorPrint.markup.includes("تقرير متابعة المدرسة") && window.__directorPrint.markup.includes("الفصل الدراسي: الفصل الدراسي الأول") && window.__directorPrint.markup.includes("A4 landscape") && !window.__directorPrint.markup.includes("أُعد محليًا على جهاز المدير"), { timeout: 30000 });
  await page.getByRole("button", { name: "مسح فلاتر التقرير", exact: true }).click();
  await page.evaluate(() => {
    Object.defineProperty(navigator, "canShare", { configurable: true, value: () => true });
    Object.defineProperty(navigator, "share", { configurable: true, value: async (payload) => { window.__aggregateShare = payload; } });
  });
  await page.getByRole("button", { name: "مشاركة", exact: true }).click();
  await page.waitForFunction(() => window.__aggregateShare?.files?.[0]?.name?.startsWith("تقرير-تجميعي-") === true, { timeout: 60000 });
  if (unexpectedDataRequests.length) throw new Error(`Aggregate report shared data without an explicit local-only path: ${unexpectedDataRequests.join(", ")}`);
  await page.evaluate(() => Object.defineProperty(navigator, "canShare", { configurable: true, value: () => false }));
  const [aggregateDownload] = await Promise.all([page.waitForEvent("download", { timeout: 60000 }), page.getByRole("button", { name: "تنزيل PDF", exact: true }).click()]);
  await aggregateDownload.saveAs(`${outputDir}/aggregate-report.pdf`);
  if (await aggregateDownload.failure()) throw new Error("Aggregate report download failed");
  await page.setViewportSize({ width: 390, height: 844 });
  const mobilePreview = await page.locator(".aggregate-report-preview").boundingBox();
  if (!mobilePreview || mobilePreview.width > 390) throw new Error("Aggregate report preview is not responsive on mobile");
  await page.setViewportSize({ width: 1280, height: 900 });
  await page.getByRole("tab", { name: "الوارد", exact: true }).click();
  await page.locator(".director-list button").filter({ hasText: "أمل السهلي" }).click();
  await page.getByRole("button", { name: "حذف الملف والتقييم", exact: true }).click();
  await page.getByRole("tab", { name: "المتابعة", exact: true }).click();
  if (await page.locator(".dashboard-stats article").nth(0).getByText("1", { exact: true }).count() !== 1) throw new Error("Dashboard total did not update after deletion");
  if (await page.locator(".dashboard-stats article").nth(1).getByText("0", { exact: true }).count() !== 1) throw new Error("Dashboard reviewed count did not update after deletion");
  if (await page.locator(".dashboard-compare-list button").count() !== 1) throw new Error("Dashboard comparison list did not update after deletion");
  if (!await page.getByRole("button", { name: "استيراد ملف PDF", exact: true }).isEnabled()) throw new Error("Director import must remain available after local review and export flows");
  console.log(`Director local import, review, persistence, and export passed: ${outputDir}`);
} finally {
  await browser.close();
}
